name: kama-games-cloud
services:

  front:
    build:
      dockerfile: packages/docker/Dockerfile.angular
      context: .
      args:
        APP: "@kama-games-cloud/front"
        DIST: "apps/front/dist/kama-games-cloud"
    image: kama-games-cloud-front
    container_name: kama-games-cloud-front
    ports:
      - "5000:5000"

  backend:
    build:
      dockerfile: packages/docker/Dockerfile.nest
      context: .
      args:
        APP: "@kama-games-cloud/backend"
        DIST: "apps/backend"
    image: kama-games-cloud-backend
    container_name: kama-games-cloud-backend
    ports:
      - "3000:3000"

  nginx:
    build:
      dockerfile: apps/nginx/Dockerfile
      context: .
    image: kama-games-cloud-nginx
    container_name: kama-games-cloud-nginx
    ports:
      - "80:80"
      - "4000:4000"
    depends_on:
      - front
    #      - kama-games-cloud-backend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'certbot certonly --webroot --webroot-path=/var/www/certbot --email tidiusff@gmail.com --agree-tos --no-eff-email -d kamalen.ddns.net'"
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --force-renewal; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-etc:
  certbot-www:
